services:

  backend:
    volumes:
      - /data/pmm/uploads:/app/uploads
    image: 10.4.102.212:8080/pmma-backend:latest
    container_name: pmma-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000

      DB_HOST: tccstock_mysql
      DB_PORT: 3306
      DB_USER: app_user
      DB_PASSWORD: app_password
      DB_NAME: app_db
    networks:
      - app-net

  frontend:
    image: 10.4.102.212:8080/pmma-client:latest
    container_name: pmma-client
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: development
      PORT: 9000
      HOSTNAME: "0.0.0.0"
      NEXT_PUBLIC_API_BASE_URL: http://10.4.102.212:5000/api
    networks:
      - app-net

networks:
  app-net:
    external: true