-- Deprecated — อย่ารันไฟล์นี้
--
-- คอลัมน์ `device_json` ถูกแทนที่ด้วย `contract_snapshot` (snapshot แถว contract + devices)
--
-- เลือกอย่างใดอย่างหนึ่ง:
--   1) DB ใหม่ / ยังไม่มี device_json:
--      mysql ... < migrations/add_contract_history_contract_snapshot.sql
--   2) เคยมี device_json แล้ว:
--      mysql ... < migrations/migrate_contract_history_device_json_to_contract_snapshot.sql
--
-- (ไม่มีคำสั่ง SQL ในไฟล์นี้)
