import type { PmFullDocument } from './types';

/** ตัวอย่างสำหรับ /dev/pm-work-order-preview — อิง template TCC PM */
export const PM_WORK_ORDER_SAMPLE: PmFullDocument = {
  inspections: [
    {
      documentTitle: 'เอกสารตรวจสอบการทำงานสภาพทั่วไป (Preventive Maintenance)',
      projectName:
        'Oishi Trading Company Limited Project Preventive Maintenance for Network Equipment',
      location: 'Oishi Trading Company Limited (Wang Muang)',
      pmNo: '2/2',
      pmDate: '2 Dec 2024',
      contactName: 'Chakkrit Aimsaard',
      contactTel: '091-757-7717',
      equipmentType: 'Core Switch',
      equipmentLocation: 'Server Room',
      hostname: 'RT-Oishi-WangMuang',
      product: 'Cisco',
      model: 'Cisco 3845',
      rackRu: 'Rack A, U38, 39, 40',
      osVersion: 'Version 15.1(4)M10, RELEASE SOFTWARE (fc2)',
      ipAddress: '10.46.76.1',
      serialNumber: 'FOC14484XBV',
      stackNo: 'No',
      stackRole: 'No',
      cpuProcessor: '2.9999999999999994E-2',
      memoryUtilization: '13.40%',
      temperature: '-',
      environmentAlarm: 'NO Alarm',
      powerSupply: '-',
      fan: 'Fan 1 OK, Fan 2 OK, Fan 3 OK',
      systemUptime: '39 weeks, 1 hour, 4 minute',
      backupConfig: 'OK',
      hardwareCleaning: 'Yes',
      comment: '',
    },
    {
      documentTitle: 'เอกสารตรวจสอบการทำงานสภาพทั่วไป (Preventive Maintenance)',
      projectName:
        'Oishi Trading Company Limited Project Preventive Maintenance for Network Equipment',
      location: 'Oishi Trading Company Limited (Wang Muang)',
      pmNo: '2/2',
      pmDate: '2 Dec 2024',
      contactName: 'Chakkrit Aimsaard',
      contactTel: '091-757-7717',
      equipmentType: 'Access Switch',
      equipmentLocation: 'Server Room',
      hostname: 'SW-Oishi-WangMuang-01',
      product: 'Cisco',
      model: 'C9300X-24Y',
      rackRu: 'Rack B, U12',
      osVersion: '17.9.4a',
      ipAddress: '10.46.76.10',
      serialNumber: 'FVH2815L4EU',
      stackNo: 'No',
      stackRole: 'No',
      cpuProcessor: '11%',
      memoryUtilization: '86.54%',
      temperature: '23',
      environmentAlarm: 'No Alarm',
      powerSupply: '23',
      fan: 'OK',
      systemUptime: '34 weeks, 1 day, 22 hours, 45 minute',
      backupConfig: 'OK',
      hardwareCleaning: 'Yes',
      comment: 'Checked all ports — no issues found.',
    },
  ],
  maintenanceChecklist: {
    date: '02 Dec 24',
    site: 'Oishi Trading Company Limited (Wang Muang)',
    rows: [
      {
        id: 'row-1',
        no: 1,
        location: 'Server Room A',
        rack: 'Rack A',
        beforePhotoSrc: null,
        afterPhotoSrc: null,
        remark: 'Cleaned dust',
      },
      {
        id: 'row-2',
        no: 2,
        location: 'Server Room B',
        rack: 'Rack B',
        beforePhotoSrc: null,
        afterPhotoSrc: null,
        remark: '',
      },
    ],
  },
};
